"""empty message

Revision ID: 38a1ea35c1ba
Revises: 
Create Date: 2023-09-06 19:22:34.217043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a1ea35c1ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=99), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('gender', sa.Enum('m', 'f', name='user_gender'), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=40), nullable=False),
    sa.Column('trim', sa.String(length=40), nullable=True),
    sa.Column('vehicle_country', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dougscores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekend_styling', sa.Integer(), nullable=False),
    sa.Column('weekend_acceleration', sa.Integer(), nullable=False),
    sa.Column('weekend_handling', sa.Integer(), nullable=False),
    sa.Column('weekend_funfactor', sa.Integer(), nullable=False),
    sa.Column('weekend_coolfactor', sa.Integer(), nullable=False),
    sa.Column('weekend_total', sa.Integer(), nullable=False),
    sa.Column('daily_features', sa.Integer(), nullable=False),
    sa.Column('daily_comfort', sa.Integer(), nullable=False),
    sa.Column('daily_quality', sa.Integer(), nullable=False),
    sa.Column('daily_practicality', sa.Integer(), nullable=False),
    sa.Column('daily_value', sa.Integer(), nullable=False),
    sa.Column('daily_total', sa.Integer(), nullable=False),
    sa.Column('dougscore_total', sa.Integer(), nullable=False),
    sa.Column('video_link', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('dougscores')
    op.drop_table('vehicles')
    op.drop_table('users')
    # ### end Alembic commands ###