"""empty message

Revision ID: d8a960825881
Revises: ffdc0a98111c
Create Date: 2023-09-06 17:37:55.414902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a960825881'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=40), nullable=False),
    sa.Column('trim', sa.String(length=40), nullable=True),
    sa.Column('vehicle_country', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dougscores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekend_styling', sa.Integer(), nullable=False),
    sa.Column('weekend_acceleration', sa.Integer(), nullable=False),
    sa.Column('weekend_handling', sa.Integer(), nullable=False),
    sa.Column('weekend_funfactor', sa.Integer(), nullable=False),
    sa.Column('weekend_coolfactor', sa.Integer(), nullable=False),
    sa.Column('weekend_total', sa.Integer(), nullable=False),
    sa.Column('daily_features', sa.Integer(), nullable=False),
    sa.Column('daily_comfort', sa.Integer(), nullable=False),
    sa.Column('daily_quality', sa.Integer(), nullable=False),
    sa.Column('daily_practicality', sa.Integer(), nullable=False),
    sa.Column('daily_value', sa.Integer(), nullable=False),
    sa.Column('daily_total', sa.Integer(), nullable=False),
    sa.Column('dougscore_total', sa.Integer(), nullable=False),
    sa.Column('video_link', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=99), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.Enum('m', 'f'), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')
        batch_op.drop_column('country')
        batch_op.drop_column('dob')
        batch_op.drop_column('gender')
        batch_op.drop_column('bio')
        batch_op.drop_column('full_name')

    op.drop_table('dougscores')
    op.drop_table('vehicles')
    # ### end Alembic commands ###