"""empty message

Revision ID: 251ff5998df2
Revises: 5d22d084ad52
Create Date: 2023-09-07 16:28:49.953935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251ff5998df2'
down_revision = '5d22d084ad52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quirks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quirk', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quirks')
    # ### end Alembic commands ###