"""empty message

Revision ID: d3a6b6de5e49
Revises: b4aefb666eca
Create Date: 2023-09-12 11:03:56.568230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a6b6de5e49'
down_revision = 'b4aefb666eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dougscores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filming_location', sa.String(length=255), nullable=True))
        batch_op.drop_column('location_id')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('vehicle_country',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('vehicle_country',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)

    with op.batch_alter_table('dougscores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('filming_location')

    # ### end Alembic commands ###