"""empty message

Revision ID: c2fb6a98e1d4
Revises: 
Create Date: 2023-09-16 12:34:37.701323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fb6a98e1d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=99), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('gender', sa.Enum('m', 'f', name='user_gender'), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=40), nullable=False),
    sa.Column('trim', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vehicle_country', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dougscores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekend_styling', sa.Integer(), nullable=False),
    sa.Column('weekend_acceleration', sa.Integer(), nullable=False),
    sa.Column('weekend_handling', sa.Integer(), nullable=False),
    sa.Column('weekend_funfactor', sa.Integer(), nullable=False),
    sa.Column('weekend_coolfactor', sa.Integer(), nullable=False),
    sa.Column('weekend_total', sa.Integer(), nullable=False),
    sa.Column('daily_features', sa.Integer(), nullable=False),
    sa.Column('daily_comfort', sa.Integer(), nullable=False),
    sa.Column('daily_quality', sa.Integer(), nullable=False),
    sa.Column('daily_practicality', sa.Integer(), nullable=False),
    sa.Column('daily_value', sa.Integer(), nullable=False),
    sa.Column('daily_total', sa.Integer(), nullable=False),
    sa.Column('dougscore_total', sa.Integer(), nullable=False),
    sa.Column('video_time', sa.String(length=8), nullable=False),
    sa.Column('video_link', sa.String(length=255), nullable=False),
    sa.Column('filming_location', sa.String(length=255), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quirks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quirk', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'vehicle_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_tags')
    op.drop_table('vehicle_images')
    op.drop_table('reviews')
    op.drop_table('quirks')
    op.drop_table('dougscores')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
