"""empty message

Revision ID: 5d22d084ad52
Revises: e585e7956981
Create Date: 2023-09-07 11:25:05.654533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d22d084ad52'
down_revision = 'e585e7956981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=99),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=99),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)

    # ### end Alembic commands ###