"""empty message

Revision ID: 2c2d691ab0ad
Revises: d553bd1820f9
Create Date: 2023-09-13 23:56:59.130139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2d691ab0ad'
down_revision = 'd553bd1820f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dougscores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_time', sa.String(length=8), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dougscores', schema=None) as batch_op:
        batch_op.drop_column('video_time')

    # ### end Alembic commands ###
